<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_En effet un formulaire ne peut prendre en_1866ab</name>
   <tag></tag>
   <elementGuidId>d9671986-af26-4f8a-9a85-cb5e33dc19e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='content']/div[2]/div/p[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>justify</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    En effet, un formulaire ne peut prendre en compte tous les éléments qui font la valeur de votre bien (luminosité, quartier, charme, atmosphère, potentiel, contexte concurrentiel, etc.). C’est pourquoi cette estimation approximative doit être affinée avec un mandataire iad expert sur votre secteur. Suite à la réception de l’évaluation du bien en ligne, le conseiller iad* pourra ensuite se déplacer à votre domicile. Il vous remettra gratuitement un avis de valeur accompagné d’une étude comparative plus poussée en fonction des prix pratiqués dans le secteur où vous êtes situé.
                </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;bg__white&quot;]/div[@class=&quot;wrapper&quot;]/p[3]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div[2]/div/p[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simulez la valeur de votre bien en ligne et bénéficiez de conseils d’un mandataire immobilier iad'])[1]/following::p[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='évaluer la valeur de votre maison,'])[1]/following::p[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='estimation immobilière en ligne'])[1]/preceding::p[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trouver un conseiller* près de chez moi'])[1]/preceding::p[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='En effet, un formulaire ne peut prendre en compte tous les éléments qui font la valeur de votre bien (luminosité, quartier, charme, atmosphère, potentiel, contexte concurrentiel, etc.). C’est pourquoi cette estimation approximative doit être affinée avec un mandataire iad expert sur votre secteur. Suite à la réception de l’évaluation du bien en ligne, le conseiller iad* pourra ensuite se déplacer à votre domicile. Il vous remettra gratuitement un avis de valeur accompagné d’une étude comparative plus poussée en fonction des prix pratiqués dans le secteur où vous êtes situé.']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p[3]</value>
   </webElementXpaths>
</WebElementEntity>
