<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bouton_retirer_de_la_selection_fiche_annonce</name>
   <tag></tag>
   <elementGuidId>644dc3db-ce48-4bf8-8bb0-3a0372ecf381</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;fiche-bien&quot;]/div[4]/div/div/div[2]/p/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
