<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mail personnel_emailPersonal-3</name>
   <tag></tag>
   <elementGuidId>f87298fb-e156-4b32-b264-49a24973d7eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='emailPersonal-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emailPersonal-3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>adresse@email.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-empty ng-valid-pattern ng-valid-email ng-not-empty-add ng-pristine-remove ng-dirty-add ng-valid-remove ng-invalid-add ng-valid-email-remove ng-invalid-email-add ng-valid-pattern-remove ng-invalid-pattern-add</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.current.obj.email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>{ allowInvalid: true }</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/^([\w-\.]+)@((?:[\w-]+\.)+)([a-zA-Z]{2,4})$/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>$ctrl.current.onItemsChange()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordiongroup-559-1965-panel&quot;)/div[@class=&quot;panel-body&quot;]/iad-my-iad-accordion-group-body[1]/div[@class=&quot;myiad-accordion-group-body&quot;]/ng-transclude[1]/div[1]/iad-my-iad-contact-information-address-form[1]/ng-form[@class=&quot;ng-valid-pattern ng-valid-required ng-valid-email ng-dirty ng-valid-mask ng-valid ng-valid-parse ng-valid-phone ng-invalid-add ng-valid-email-remove ng-invalid-email-add ng-valid-pattern-remove ng-invalid-pattern-add&quot;]/iad-block[2]/section[@class=&quot;iad-block margin-top-20&quot;]/div[@class=&quot;iad-block-content clearfix&quot;]/iad-block-body[1]/iad-my-iad-add-remove-extended[1]/div[@class=&quot;row margin-top-20&quot;]/div[1]/div[@class=&quot;col-xs-11&quot;]/iad-my-iad-add-remove-extended-item[1]/iad-component-body[1]/iad-my-iad-contact-information-complexe-email-input[1]/div[@class=&quot;myiad-contact-phone-email&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-12 form-group&quot;]/div[@class=&quot;col-sm-7&quot;]/iad-form-group[1]/div[@class=&quot;iad-form-group form-group  has-feedback&quot;]/input[@class=&quot;form-control ng-pristine ng-untouched ng-valid ng-empty ng-valid-pattern ng-valid-email ng-not-empty-add ng-pristine-remove ng-dirty-add ng-valid-remove ng-invalid-add ng-valid-email-remove ng-invalid-email-add ng-valid-pattern-remove ng-invalid-pattern-add&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='emailPersonal-3']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-559-1965-panel']/div/iad-my-iad-accordion-group-body/div/ng-transclude/div/iad-my-iad-contact-information-address-form/ng-form/iad-block[2]/section/div/iad-block-body/iad-my-iad-add-remove-extended/div[2]/div/div/iad-my-iad-add-remove-extended-item/iad-component-body/iad-my-iad-contact-information-complexe-email-input/div/div/div/div[2]/iad-form-group/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iad-my-iad-contact-information-complexe-email-input/div/div/div/div[2]/iad-form-group/div/input</value>
   </webElementXpaths>
</WebElementEntity>
