<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_previous</name>
   <tag></tag>
   <elementGuidId>fa6de2c9-fa29-4e0a-a6f8-e47d415961e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@type = 'button' and (text() = 'previous' or . = 'previous')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm pull-left uib-left</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>move(-1)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>previous</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordiongroup-554-1625-panel&quot;)/div[@class=&quot;panel-body&quot;]/iad-my-iad-accordion-group-body[1]/div[@class=&quot;myiad-accordion-group-body&quot;]/ng-transclude[1]/div[1]/iad-my-iad-contact-identity-form[1]/div[@class=&quot;ng-valid myiad-form-node myiad-form-node-root physical_contact ng-valid-date ng-dirty ng-valid-parse ng-valid-date-disabled&quot;]/div[@class=&quot;myiad-form-node-row myiad-form-node-greetings&quot;]/div[@class=&quot;myiad-form-node-col myiad-form-node-birth-date col-xs-12 col-sm-6&quot;]/div[@class=&quot;myiad-form-node-group&quot;]/iad-form-group[1]/div[@class=&quot;iad-form-group form-group has-feedback&quot;]/div[@class=&quot;input-group&quot;]/div[@class=&quot;ng-pristine ng-untouched ng-valid ng-empty ng-valid-date-disabled&quot;]/ul[@class=&quot;uib-datepicker-popup dropdown-menu&quot;]/li[1]/div[@class=&quot;uib-datepicker&quot;]/div[1]/div[@class=&quot;uib-yearpicker&quot;]/table[1]/thead[1]/tr[1]/th[1]/button[@class=&quot;btn btn-default btn-sm pull-left uib-left&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-554-1625-panel']/div/iad-my-iad-accordion-group-body/div/ng-transclude/div/iad-my-iad-contact-identity-form/div/div/div[2]/div/iad-form-group/div/div/div[2]/ul/li/div/div/div/table/thead/tr/th/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date de naissance'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nom de jeune fille'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='next'])[1]/preceding::button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
   </webElementXpaths>
</WebElementEntity>
