<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Lorsque vous avez termin, cliquez sur le bouton de validation._rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>1f2c0f04-cd8d-4c5d-947a-148be05f4fcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq25MdRdxD2IL8hHFM6pz9jcbiqCTwwkDBjz2UZAnGfKTHR8FIPoFWicVZvE6Qnk27e-ztJKu_uXWWWH4NSWD_lCQGyULKR4WHMqdo-oMjQNl4vHNJ6BHl96ogEe3cBapztG5_75QwhtrwFXtNvTEjTXvdLqGS5ZkCyjn8eYjH6MZYNucy-Zmx2eaz504nmsMcNDPBYi6&amp;k=6LcHUDMUAAAAAFBXx95-QDYk35xfsxW2jX-vxcSx</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_iad - Vente, achat, location, maison, _20b116/iframe_FERMER_c-al2dn2kmcpuc</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq25MdRdxD2IL8hHFM6pz9jcbiqCTwwkDBjz2UZAnGfKTHR8FIPoFWicVZvE6Qnk27e-ztJKu_uXWWWH4NSWD_lCQGyULKR4WHMqdo-oMjQNl4vHNJ6BHl96ogEe3cBapztG5_75QwhtrwFXtNvTEjTXvdLqGS5ZkCyjn8eYjH6MZYNucy-Zmx2eaz504nmsMcNDPBYi6&amp;k=6LcHUDMUAAAAAFBXx95-QDYk35xfsxW2jX-vxcSx')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
   </webElementXpaths>
</WebElementEntity>
