<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__valider</name>
   <tag></tag>
   <elementGuidId>e0c8174c-ea90-4640-8ca0-395b8aa12fc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Calculer']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;tableau_donnees&quot;)/tbody[1]/tr[6]/td[@class=&quot;tableau_donnees_droite&quot;]/input[@class=&quot;valider&quot;][count(. | //input[@type = 'submit' and @value = 'Calculer' and @class = 'valider' and @ref_element = 'Object Repository/calculerMensualité/Page_iad - Bureaux de 110 m - PARIS/iframe_Calculateur de mensualit de bien_cal_f81540']) = count(//input[@type = 'submit' and @value = 'Calculer' and @class = 'valider' and @ref_element = 'Object Repository/calculerMensualité/Page_iad - Bureaux de 110 m - PARIS/iframe_Calculateur de mensualit de bien_cal_f81540'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Calculer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valider</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableau_donnees&quot;)/tbody[1]/tr[6]/td[@class=&quot;tableau_donnees_droite&quot;]/input[@class=&quot;valider&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/calculerMensualité/Page_iad - Bureaux de 110 m - PARIS/iframe_Calculateur de mensualit de bien_cal_f81540</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Calculer']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tableau_donnees']/tbody/tr[6]/td[2]/input[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
   </webElementXpaths>
</WebElementEntity>
