<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Haz clic en Verificar cuando no quede ninguna._rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>159bd57a-5630-4cee-9325-a4dcd0f48301</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-33</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq27WAyB5OfUbpHkdlb0WGsg21G7RhygZ_ODkr4YHQC8PyzzgdR80Fb0lt_6V4ZP2oM-X1K0szHs7e0U2FMUrm3GQLR_Jvqfo9ign0cn5WP-Z7PZgvkoOF8irrl5FaFEVSLdkWSIuoV1rV4xg6I-ZiEQW1p_rJ9vOFUjl7k3IqY-zBojI_oWHUi2bUOgAXwrKD5ANpNQ0&amp;k=6Lc5dHYUAAAAANnjXh_gjvT_bYuTTg97VWdX8w_S</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_iad - Venta Chalet Llber 340 m 4 dormitorios/iframe_CERRAR_c-ggve06e8g2c</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq27WAyB5OfUbpHkdlb0WGsg21G7RhygZ_ODkr4YHQC8PyzzgdR80Fb0lt_6V4ZP2oM-X1K0szHs7e0U2FMUrm3GQLR_Jvqfo9ign0cn5WP-Z7PZgvkoOF8irrl5FaFEVSLdkWSIuoV1rV4xg6I-ZiEQW1p_rJ9vOFUjl7k3IqY-zBojI_oWHUi2bUOgAXwrKD5ANpNQ0&amp;k=6Lc5dHYUAAAAANnjXh_gjvT_bYuTTg97VWdX8w_S')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
   </webElementXpaths>
</WebElementEntity>
