<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_submit</name>
   <tag></tag>
   <elementGuidId>b85eb618-f16e-4d38-8732-4edeef530c02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;profile_form&quot;]/div[7]/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;profile_form&quot;]/div[7]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;profile_form&quot;]/div[7]/button</value>
   </webElementProperties>
</WebElementEntity>
