<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_phone_number</name>
   <tag></tag>
   <elementGuidId>97dfba6d-89cc-41f6-8a82-7e308cf74c64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;phoneNumberId&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>#phoneNumberId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#phoneNumberId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;phoneNumberId&quot;]</value>
   </webElementProperties>
</WebElementEntity>
