<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_first_name_nom_famille</name>
   <tag></tag>
   <elementGuidId>d76e9404-4c2d-40c1-8271-a3dffc2efcd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#firstNameId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;firstNameId&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>firstNameId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>firstNameId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;firstNameId&quot;]</value>
   </webElementProperties>
</WebElementEntity>
