<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_gender_Sig.ra</name>
   <tag></tag>
   <elementGuidId>78b35fd0-8ca6-463b-b8ab-d4a0745b0ccc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mrs</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
