<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_gender_sig</name>
   <tag></tag>
   <elementGuidId>18fb3675-f172-4dc1-aec8-120dd17fd2a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mr</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
