<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_liste_des_genres_proposes</name>
   <tag></tag>
   <elementGuidId>82503ef0-ee6e-43ea-9cb8-9e5a15a1566b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#genderId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;genderId&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>#genderId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;genderId&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#genderId</value>
   </webElementProperties>
</WebElementEntity>
