<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_pasos de peatones_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>f5499983-eb1f-4420-8234-bf10f6a22665</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq26J9Z4eQym3HgSC8TZ9fT99DSZCdxmbCz-LY67GWsaXpiWFagLWAMnmxAGpw5_VJGmmbK0sHw8vTjct73l98PXKS7qPkZSMmNKp--rCzyjuxNmye8-9pi2U6xk-bgvIjbA4RjmFPSWKg6ye0JCpjb5KnwtWKvC4r75PNURtvHXhbNRKJMN6T8LMILsYkUpJwDgPlRd4&amp;k=6Lc5dHYUAAAAANnjXh_gjvT_bYuTTg97VWdX8w_S</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/me contacter mini conseiller-prestige ES/iframe_CERRAR_c-vjli4p90ej0</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq26J9Z4eQym3HgSC8TZ9fT99DSZCdxmbCz-LY67GWsaXpiWFagLWAMnmxAGpw5_VJGmmbK0sHw8vTjct73l98PXKS7qPkZSMmNKp--rCzyjuxNmye8-9pi2U6xk-bgvIjbA4RjmFPSWKg6ye0JCpjb5KnwtWKvC4r75PNURtvHXhbNRKJMN6T8LMILsYkUpJwDgPlRd4&amp;k=6Lc5dHYUAAAAANnjXh_gjvT_bYuTTg97VWdX8w_S')])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
